# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        poetry-version: ["1.7.1"]
    runs-on: ubuntu-latest
    env:
      SOURCE_FILES: code_size_counter tests/test_code_size_counter.py
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.3.0      
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install dependencies
      run: poetry install
    - name: Check formatting
      run: poetry run black --check $SOURCE_FILES
    - name: Lint with flake8
      run: poetry run flake8 $SOURCE_FILES
    - name: Test with unittest module
      run: |
        poetry run python -m unittest discover tests -v
